[package]
name = "rjg"
version = "0.1.0"
edition = "2024"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
license = "MIT"
description = "Random JSON Generator"
homepage = "https://github.com/sile/rjg"
repository = "https://github.com/sile/rjg"
readme = "README.md"

[dependencies]
noargs = "0.2.0"
rand = "0.9.0"
rand_chacha = "0.9.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
