[package]
name = "rjg"
version = "0.3.0"
edition = "2024"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
license = "MIT"
description = "Random JSON Generator"
homepage = "https://github.com/sile/rjg"
repository = "https://github.com/sile/rjg"
readme = "README.md"

[dependencies]
noargs = "0.4.1"
nojson = "0.3.6"
rand = "0.9.0"
rand_chacha = "0.9.0"
